### ISSUE TITLE
[Servlet-001] : Upgrade UI as per latest release of the API 17.10

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-conversion/GroupDocs.Conversion-for-Java#22]
Please update the showcase project as per new release of the API. There is following error while updating the UI:
**cannot convert from ConvertedDocument to GroupDocsInputStream**.

**Comment by rwstauner** [comment]
This would be greatly appreciated.  With 17.3 I was using an IOuputHandler to get each image from a pptx.  On 17.10 it is never called, and calling .save on the new ConvertedDocument result throws an error.

**Comment by atirtahirgroupdocs** [comment]
@rwstauner,

We are investigating the issue. You shall be notified about the outcomes.

**Comment by bobkovalex** [comment]
Please refer to new front-end examples for the fix:
https://github.com/groupdocs-conversion/GroupDocs.Conversion-for-Java-Dropwizard
https://github.com/groupdocs-conversion/GroupDocs.Conversion-for-Java-Spring
