### ISSUE TITLE
Upgrade GroupDocs.Conversion Spring application to latest version 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-conversion/GroupDocs.Conversion-for-Java#48]
his issue is raised in https://forum.groupdocs.com/t/spring-demo-not-converting/10722/4

Hi,
Could you please upgrade [this](https://github.com/groupdocs-conversion/GroupDocs.Conversion-for-Java/tree/master/Demos/Spring) demo application? It uses a very old version of the API (19.4) and the latest version is 21.10.1. 
Cannot build the application, it gives following exception:

> Could not resolve dependencies for project com.groupdocs.ui:conversion-spring:jar:0.0.9: Failed to collect dependencies at com.groupdocs:groupdocs-conversion:jar:19.4

Thanks

**Comment by nikola-yankov** [comment]
@atirtahirgroupdocs The Spring application has been updated.
